# Configure main menu and social menu

#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1



[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Aditya-dom"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Aditya_dom10"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/adi-dom/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "Instagram"
name = "Instagram"
url = "https://www.instagram.com/arawn_.10/"

[social.params]
icon = "brand-instagram"





