# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
[main.params]
icon = "home"
newtab = true

[[main]]
identifier = "About me"
name = "About me"
url = "/about"
[main.params]
icon = "about"
newtab = true

[[main]]
identifier = "blog"
name = "Blog"
url = "/blog"
[main.params]
icon = "blog"
newtab = true

[[main]]
identifier = "projects"
name = "Projects"
url = "/projects"
[main.params]
icon = "projects"
newtab = true



[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Aditya-dom"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Aditya_dom10"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/adi-dom/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/arawn_.10/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "RSS"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"
