# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
[main.params]
icon = "home"
newtab = true

[[main]]
identifier = "superhuman"
name = "Superhuman"
url = "/superhuman"
[main.params]
icon = "superhuman"
newtab = true


[[main]]
identifier = "device-projector"
name = "Projects"
url = "/projects"
[main.params]
icon = "device-projector"
newtab = true


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Aditya-dom"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Aditya_dom10"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/adi-dom/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/arawn_.10/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "RSS"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"
