# Configure main menu and social menu

#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Aditya-dom"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Aditya_dom10"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/adi-dom/"

[social.params]
icon = "brand-linkedin"

#[[social]]
#identifier = "instagram"
#name = "Instagram"
#url = "https://www.instagram.com/arawn_.10/"

#[social.params]
#icon = "brand-instagram"

# Configure the RSS feed
rss = true
show_rss_icon = true
rss_title = "Subscribe to my feed"
rss_description = "Stay up to date with my latest posts"

